---

- name: Create rabbitmq config dir
  file:
    path:   "{{ rabbitmq_conf_dir }}"
    owner:  root
    group:  root
    mode:   0755
    state:  directory

- name: Create rabbitmq ssl config dir
  file:
    path:   "{{ rabbitmq_conf_dir }}/ssl"
    owner:  root
    group:  root
    mode:   0755
    state:  directory

- name: Create rabbitmq config file
  template:
    src:    rabbitmq.config.j2
    dest:   "{{ rabbitmq_conf_dir }}/rabbitmq.config"
    owner:  root
    group:  root
    mode:   0644
  notify: Restart rabbitmq-server

- name: Create rabbitmq environment config file
  template:
    src:    rabbitmq-env.conf.j2
    dest:   "{{ rabbitmq_conf_dir }}/rabbitmq-env.conf"
    owner:  root
    group:  root
    mode:   0644
  notify: Restart rabbitmq-server

- name: Create rabbitmq admin config file
  template:
    src:    rabbitmqadmin.conf.j2
    dest:   "{{ rabbitmq_conf_dir }}/rabbitmqadmin.conf"
    owner:  root
    group:  root
    mode:   0644

- name: Update rabbitmq-server startup script envrionment variables file
  template:
    src:    etc.default.rabbitmq-server.j2
    dest:   /etc/default/rabbitmq-server
    owner:  root
    group:  root
    mode:   0644
  notify: Restart rabbitmq-server

- name: Create rabbitmq-server logrotate config file
  template:
    src:   rabbitmq-server.logrotate.j2
    dest:  /etc/logrotate.d/rabbitmq-server
    owner: root
    group: root
    mode:  0644

- name: Configure security limits for rabbitmq
  template:
    src:    system-limits.conf.j2
    dest:   /etc/security/limits.d/rabbitmq-server.conf
    owner:  root
    group:  root
    mode:   0644
  notify: Restart rabbitmq-server

## For systemd
#- name: Create rabbitmq systemd service config dir
#  file:
#    path:   /etc/systemd/system/rabbitmq-server.service.d
#    owner:  root
#    group:  root
#    mode:   0755
#    state:  directory
#
#- name: Configure limits for rabbitmq service
#  template:
#    src:    service-limits.conf.j2
#    dest:   /etc/systemd/system/rabbitmq-server.service.d/limits.conf
#    owner:  root
#    group:  root
#    mode:   0644
#  register: limits
#
#- name: Rabbitmq systemd reload
#  command: /usr/bin/systemctl daemon-reload
#  when: limits|changed
