---

- name: Enable rabbitmq plugins
  rabbitmq_plugin:
    names:    "{{ rabbitmq_plugins_enable|join(',') }}"
    new_only: no
    state:    enabled
  when: rabbitmq_plugins_enable|default([])

- name: Disable rabbitmq plugins
  rabbitmq_plugin:
    names:    "{{ rabbitmq_plugins_disable|join(',') }}"
    new_only: no
    state:    disabled
  when: rabbitmq_plugins_disable|default([])
